### ISSUE TITLE
DevBox with DHCP

### ISSUE THREAD

**Issue by minhoryang** [vmware/photon-controller#1]
Is there any way to set DHCP and contact /api

I tried to change /etc/systemd/network to certain ip from dhcp pool, but can't contact with /api

**Comment by minhoryang** [comment]
Oh I used .ova version.
I also tried to ssh port-forward thingy, but failed.

**Comment by minhoryang** [comment]
build java/*, but don't know run it.
I'll retry with devbox vagrant options tomorrow.

**Comment by kmjung** [comment]
Hi, this question is probably better asked on our Google group (https://groups.google.com/group/photon-controller). This forum is intended for code issues rather than user issues.
