### ISSUE TITLE
Error: Could not find Auth-Token tool under /photon-controller/ruby/cli/lib/cli/commands/../../../assets

### ISSUE THREAD

**Issue by dbmlabs** [vmware/photon-controller#10]
All,

What would cause the auth-token tool to not get installed?  I am trying to get the latest photon binary to work with an endpoint. I followed the instructions on github
1.  gem install bundler
2. run_ci.sh
3. bundle install

Using target 'https://1.2.3.4'
Logging in user@example.com ...
Error: Could not find Auth-Token tool under /photon-controller/ruby/cli/lib/cli/commands/../../../assets

Any help?  thank you.

**Comment by molteanu** [comment]
If auth-tool is a java executable built out of: /photon-controller/java/auth-tool is you execute "../gradlew clean build" in that folder it will build the jar and place it in the folder the CLI requires it in.

**Comment by dbmlabs** [comment]
Hi @molteanu Thanks for the quick response.  I ran the command and the result was:

Gradle suite > Gradle test > com.vmware.photon.controller.auth.ClientRegistrationArgumentsTest.gettersTest PASSED

Gradle suite > Gradle test > com.vmware.photon.controller.auth.MainTest.verifyGetAccessTokenByPassword PASSED

Gradle suite > Gradle test > com.vmware.photon.controller.auth.MainTest.verifyGetRefreshToken PASSED

Gradle suite > Gradle test > com.vmware.photon.controller.auth.MainTest.verifyRegisterClient PASSED
:auth-tool:check
:auth-tool:build

BUILD SUCCESSFUL

Total time: 2 mins 27.157 secs

However, I am still running into the error.  The assets directory does not exist still.

Thanks for your help.  Let me know if there are any log files I can help provide.
