### ISSUE TITLE
Deleting a photon image doesn't delete it from the associated datastore

### ISSUE THREAD

**Issue by mrporcles** [vmware/photon-controller#101]
Deleting an image using ./photon image delete does not delete the corresponding image from the datastore of the hosts.

[imgdeletecli.txt](https://github.com/vmware/photon-controller/files/851260/imgdeletecli.txt)
<img width="583" alt="screen shot 2017-03-17 at 17 01 05" src="https://cloud.githubusercontent.com/assets/8677171/24054208/5e8de6ce-0b33-11e7-997b-df57a6fcc938.png">

**Comment by AlainRoy** [comment]
Image deletion happens in the background and it can take a while if the image has been replicated to a lot of hosts. How long did you wait?

**Comment by mrporcles** [comment]
30 minutes and it is still in the datastore. I deleted another one previously (10 minutes before) as well and that one is also still there. I see a unused_image_marker file. Does it make use of this?

**Comment by mrporcles** [comment]
The deletion seems to have worked after leaving it overnight

**Comment by AlainRoy** [comment]
Did it take "overnight", or you just didn't look at it for a while after the 30 minute mark?

From my reading of the code: every 60 minutes, we remove images that haven't been used in at least 30 minutes. (We don't remove the images immediately--it's part of a larger image cleaning process.) Depending on the time you deleted it relative to this background processing, it could be up to 90 minutes to delete it. (If I did my math right--I'm not quite awake yet.)
