### ISSUE TITLE
lightwave password not checked by installer

### ISSUE THREAD

**Issue by vChrisR** [vmware/photon-controller#102]
When trying to install photon platform I ran into an issue: The lightwave appliance was deployed successfully but never lightwave never came online. Errors in the photon-installer.log look like this: 

```
2017-03-24 15:01:21 DEBUG LightwaveController:197 - Info: Checking Lightwave at <ip>
2017-03-24 15:01:21 DEBUG PhotonSetupImpl:66 - Info: Checking if Lightwave service is running at <ip>
```

This times out after 300 retries. 
When I changedd the yaml entry for lightwave.credential.password to contain a more complex password the installation went fine. 

Imho the installer should check for this because currently there is no meaningful error. Took me a while to figure out what was wrong. If the installer checks for the password complexity that might save other users a lot of time.

**Comment by AlainRoy** [comment]
Good catch--we should have done this. I added a check to the installer for this, and it will be in the 1.2 release. Thanks for reporting it!
