### ISSUE TITLE
Error in kubectl get pods --all-namespaces

### ISSUE THREAD

**Issue by terpsho** [vmware/photon-controller#118]
[Info]
    I successfully created a kubenetes cluster using photon controller. However, I failed to create a workable username/password in using kubectl functionalities. 

[Photon Platform version]
1.2.0. Released on Jan. 2017 Change-Id: Idee45cd858fb95421eedbc1d61d0226a3b37d350

[Steps to replicate this issue]
1. Copy kubectl to /usr/local/bin 
2. Username/Password was created using photon service get-kubectl-auth
`
    photon service get-kubectl-auth -u administrator@shawn.local \
         -p 'VMware1!' 4e6993c6-0f70-4933-abf5-60712f23bd0b
`
3. Execute the returned string. The returned result shows User "administrator@shawn.local" set.
4. Following https://github.com/vmware/photon-controller/wiki/Creating-a-Kubernetes-Cluster to set cluster and context as "default-cluster" and "default-system", respectively. Returned messages are all normal.
5. Set to use default-system as content.
6. 'kubectl get pods --all-namespaces' returned  `Unable to connect to the server: oidc: JWT claims invalid: token is expired`

[What's expected]
It should return pods information.

**Comment by shawnho1018** [comment]
Thanks @AlainRoy. You're right about the incorrect time. The deployed VM was not synchronised with respect to the host, which in turn causes time difference. After configuring VMtool to sync with host, this issue is resolved. Thanks for your and @Michael West's help. Please close the ticket.

**Comment by AlainRoy** [comment]
Thanks for letting us know.
