### ISSUE TITLE
Unable to install photon controller on esxi hosts

### ISSUE THREAD

**Issue by upuvvad1** [vmware/photon-controller#135]
I am new to the environment and wanted to test it in a lab environment.

Here is my config.yaml file
[test.yaml.txt](https://github.com/vmware/photon-controller/files/1089797/test.yaml.txt)

I am running on ESXi 6.0 hosts and all the controllers are on the same machine.

root@photon-installer [ ~ ]# photon-setup platform install -config test.yaml
**Using configuration at test.yaml
java.io.IOException: Error: The config file was not parsed correctly**

Can someone point out, what's going wrong with the config file?
I cross checked my YAML file, across validator online, and it responded with valid.

**Comment by It4lik** [comment]
Only ESXi 6.5 with a specific patch seems to be supported, see [here in the wiki](https://github.com/vmware/photon-controller/wiki/Release-Notes#supported-platforms). 

But indeed, this error is directly related to your YAML file. Yep, using http://www.yamllint.com/ it looks valid. 
But : 
* You specify a hostname with a **@** in it on line 46
* I don't know if it's important but "Static" is written in lowercase in the official templates, try with "**static**".

**Comment by upuvvad1** [comment]
@It4lik 
Thanks for directing me towards correct direction.
I configured my machine with esxi 6.5.0 and applied the patch mentioned in the documents.
It still returns out with the same error.

`root@photon-installer [ ~ ]# photon-setup platform install -config ./test_config.yaml
`
Using configuration at ./test_config.yaml
Exception in thread "main" java.io.IOException: Error: The config file was not parsed correctly
        at com.vmware.photon.platform.setup.PlatformConfiguration.build(PlatformConfiguration.java:124)
        at com.vmware.photon.platform.setup.PlatformInstaller.build(PlatformInstaller.java:336)
        at com.vmware.photon.platform.setup.PhotonSetup.main(PhotonSetup.java:47)

**Comment by pompomJuice** [comment]
I noticed that applying vmware patches to match photon-controller needs failed before. I had to install the correct version from scratch. You might try that. And are you running nested ESXi?
