### ISSUE TITLE
photon-controller installer hangs...

### ISSUE THREAD

**Issue by tk-knows** [vmware/photon-controller#146]
Can you please check following config (attached file)?
The yaml config file was verified at http://www.yamllint.com.

We are just following the "basic configuration " one-ESXI6.5 box deployment for development/testing [from section 4.4. quick start guide](https://vmware.github.io/photon-controller/assets/files/photon-controller-quick-start-guide-1.1.pdf)

Attached the Yaml configuration file.  On running the installer, it hangs for a long time. The log file is also attached.

[photon-controller.log.txt](https://github.com/vmware/photon-controller/files/1911511/photon-controller.log.txt)
[photon-controller-config2.yaml.txt](https://github.com/vmware/photon-controller/files/1911514/photon-controller-config2.yaml.txt)

**Comment by AlainRoy** [comment]
Photon Controller is no longer maintained or supported:
https://github.com/vmware/photon-controller/blob/master/README.md

My memory is there may be a problem with VMs due to an expired password. That may be the problem here.
