### ISSUE TITLE
Several typos on "Preparing for Cluster Deployments" Wiki

### ISSUE THREAD

**Issue by lamw** [vmware/photon-controller#18]
The following Wiki page https://github.com/vmware/photon-controller/wiki/preparing-for-cluster-deployments has several typos

1) P and D should not be capital

`Photon Deployment list`

should be

`photon deployment list
`
2) There's a space in the -k option

```
photon deployment enable-cluster-type "deployment_ID" - k KUBERNETES -i "Kubernetes Image ID"
photon deployment enable-cluster-type "deployment_ID" - k MESOS -i "MESOS Image ID"
photon deployment enable-cluster-type "deployment_ID" - k SWARM -i "SWARM Image ID"
```

should be

```
photon deployment enable-cluster-type "deployment_ID" -k KUBERNETES -i "Kubernetes Image ID"
photon deployment enable-cluster-type "deployment_ID" -k MESOS -i "MESOS Image ID"
photon deployment enable-cluster-type "deployment_ID" -k SWARM -i "SWARM Image ID"
```

**Comment by pdellaert** [comment]
I think you can make those changes yourself (well, i just did it, can't imagine you wouldn't have access to it)

**Comment by lamw** [comment]
Just noticed the *Edit* button. Thanks
