### ISSUE TITLE
Photon Controller CLI with Ubuntu

### ISSUE THREAD

**Issue by minhoryang** [vmware/photon-controller#2]
According to Photon_Controller_Getting_Started_Guide_20151116.pdf, I tried to find GO CLI.
But it was Ruby CLI... :)

**Comment by mwest44** [comment]
During Alpha/Early Beta of Photon Controller we exclusively used the Ruby CLI.  It is included with the repo.  We have been working on a GO based CLI.  This is the CLI included as a binary for you to use when trying the laptop dev environment.  I don't think we have included it in the repo at this point.

**Comment by minhoryang** [comment]
Thanks for reading this and kindly explaining this. +1
