### ISSUE TITLE
ESXi Installer OVA: Deployment disregards vApp properties?

### ISSUE THREAD

**Issue by pdellaert** [vmware/photon-controller#20]
Whenever i deploy the OVA, it seems to disregard the network settings i set in the vApp properties. 

Tried it with the C# client and the ovftool:
```
ovftool --acceptAllEulas --noSSLVerify --net:"NAT=Management" --datastore="esxi1" --diskMode="thin" —powerOn —-name=“PHC-INSTALL" --prop:"ip0=10.189.2.70” --prop:"netmask0=255.0.0.0" --prop:"gateway=10.0.0.1" --prop:"DNS=10.189.2.254" --prop:"ntp_servers=10.189.2.254" installer-vm.ova vi://vc01.intern.testlab.org/Main/host/Management
```

**Comment by ruurdk** [comment]
This apparently a known issue. A workaround when using vCenter: http://www.virtuallyghetto.com/2016/04/caveat-when-deploying-photon-controller-installer-v0-8-ova-to-vcenter-server.html

What worked for me on standalone ESXi:
`ovftool --prop:enable_syslog="true" --prop:syslog_endpoint= --acceptAllEulas --noSSLVerify --skipManifestCheck --X:injectOvfEnv --overwrite --powerOffTarget --powerOn --diskMode=thin --net:"NAT"="VM Network" --datastore="vsan_virtualized_nfs" --name=Photon-Controller-Installer0-8 --prop:ip0=192.168.10.253 --prop:netmask0=255.255.255.0 --prop:gateway=192.168.10.1 --prop:DNS=192.168.10.2 --prop:ntp_servers= --prop:admin_password=adminpass installer-vm.ovf vi://esxadmin:esxadminpass@esxip`

**Comment by tssgery** [comment]
We noticed the same thing the key being to add the --X:injectOvfEnv and
--powerOn options to ovftool

**Comment by pdellaert** [comment]
Thanks for the workaround!
