### ISSUE TITLE
Devbox build failed due to inaccessible vmware site link

### ISSUE THREAD

**Issue by chenl23** [vmware/photon-controller#23]
Trying to build devbox from source on my Mac. "Vagrant up” worked fine for me. When I tried to use prepare-devbox-deployment.sh, it failed because the package I sent below cannot be accessed. I commented it out temporarily to move forward and finally got the devbox up. 
https://ci.ec.eng.vmware.com/view/UI/job/ec-ui-mgmt-publish-docker-image-develop/lastSuccessfulBuild/artifact/ci/docker-image/esxcloud-management-ui.tar

**Comment by kmjung** [comment]
Thanks for pointing out this issue. Deployment from devbox is not a supported scenario in 0.8 -- it's something that we use for our internal CI purposes only. Please deploy using the installer OVA from the download page instead.

**Comment by chenl23** [comment]
I see. Then can you please indicate that in README file of Devbox, to avoid other people wasting time try it out.

**Comment by kmjung** [comment]
Fair request. Change forthcoming.

**Comment by kmjung** [comment]
@chenl23: https://github.com/vmware/photon-controller/commit/b49e79c396f959668ae8d31224ca86703194a0ef
