### ISSUE TITLE
Error while deploy mesos cluster

### ISSUE THREAD

**Issue by julykobe** [vmware/photon-controller#25]
### I'm trying to setup a mesos cluster on PC, but failed at deploy mesos masters. 

```
➜  Downloads ./photon cluster create -n Mesos2 -k MESOS --dns 10.110.160.1 --gateway 10.110.170.253 --netmask 255.255.255.0 --zookeeper1 10.110.170.51 -s 2
Using target 'http://10.110.170.48:9000'
Zookeeper server 2 static IP address (leave blank for none):

Creating cluster: Mesos2 (MESOS)
  Slave count: 2

Are you sure [y/n]? y
2016/04/20 13:10:34 photon: Task '5633278a-f47e-41f1-9c10-4873b95f850b' is in error state: {@step=={"sequence"=>"2","state"=>"ERROR","errors"=>[photon: { HTTP status: '0', code: 'InternalError', message: 'Failed to rollout MesosMaster. Error: MultiException[java.lang.IllegalStateException: ClusterWaitTaskService failed with error Wait period expired. /photon/clustermanager/wait-for-cluster-tasks/c008a5dd-eef7-4018-bb47-c3bb0ec0c74a, java.lang.IllegalStateException: ClusterWaitTaskService failed with error Wait period expired. /photon/clustermanager/wait-for-cluster-tasks/129a2e3b-3de7-4f39-b75a-502f61d08ad8, java.lang.IllegalStateException: ClusterWaitTaskService failed with error Wait period expired. /photon/clustermanager/wait-for-cluster-tasks/9d203664-b548-4106-b2ec-0272ada2310c]', data: 'map[]' }],"warnings"=>[],"operation"=>"CREATE_MESOS_CLUSTER_SETUP_MASTERS","startedTime"=>"1461128267000","queuedTime"=>"1461128212000","endTime"=>"1461128917000","options"=>map[]}}
API Errors: [photon: { HTTP status: '0', code: 'InternalError', message: 'Failed to rollout MesosMaster. Error: MultiException[java.lang.IllegalStateException: ClusterWaitTaskService failed with error Wait period expired. /photon/clustermanager/wait-for-cluster-tasks/c008a5dd-eef7-4018-bb47-c3bb0ec0c74a, java.lang.IllegalStateException: ClusterWaitTaskService failed with error Wait period expired. /photon/clustermanager/wait-for-cluster-tasks/129a2e3b-3de7-4f39-b75a-502f61d08ad8, java.lang.IllegalStateException: ClusterWaitTaskService failed with error Wait period expired. /photon/clustermanager/wait-for-cluster-tasks/9d203664-b548-4106-b2ec-0272ada2310c]', data: 'map[]' }]
```

## one zk and three mesos master vm have been created and IP has been allocated. I check the deploy.log, found:

```
WARN  [2016-04-20 05:08:35,608] com.vmware.photon.controller.clustermanager.statuschecks.MesosStatusChecker: Mesos call failed:
! java.net.ConnectException: Connection refused
! at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
! at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
! at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvent(DefaultConnectingIOReactor.java:173)
! at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:147)
! at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:348)
! at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:189)
! at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.doExecute(CloseableHttpAsyncClientBase.java:67)
! at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.access$000(CloseableHttpAsyncClientBase.java:38)
! at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:57)
! at java.lang.Thread.run(Thread.java:745)
ERROR [2016-04-20 05:08:35,608] com.vmware.photon.controller.clustermanager.tasks.ClusterWaitTaskService: [/photon/clustermanager/wait-for-cluster-tasks/9d203664-b548-4106-b2ec-0272ada2310c] java.lang.IllegalStateException: Wait period expired
        at com.vmware.photon.controller.clustermanager.tasks.ClusterWaitTaskService.processTask(ClusterWaitTaskService.java:175)
        at com.vmware.photon.controller.clustermanager.tasks.ClusterWaitTaskService.access$000(ClusterWaitTaskService.java:52)
        at com.vmware.photon.controller.clustermanager.tasks.ClusterWaitTaskService$1.onSuccess(ClusterWaitTaskService.java:129)
        at com.vmware.photon.controller.clustermanager.tasks.ClusterWaitTaskService$1.onSuccess(ClusterWaitTaskService.java:125)
        at com.vmware.photon.controller.clustermanager.statuschecks.MesosStatusChecker$1.onFailure(MesosStatusChecker.java:54)
        at com.vmware.photon.controller.clustermanager.statuschecks.MesosStatusChecker$3.onFailure(MesosStatusChecker.java:113)
        at com.vmware.photon.controller.clustermanager.clients.MesosClient$1.failed(MesosClient.java:100)

```

## cloud-init.log from one mesos master: ##

```
2016-04-20 04:57:59,530 - util.py[WARNING]: Unable to change the ownership of /var/log/cloud-init.log to user syslog, group adm
2016-04-20 04:57:59,530 - util.py[DEBUG]: Unable to change the ownership of /var/log/cloud-init.log to user syslog, group adm
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cloudinit/stages.py", line 156, in _initialize_filesystem
    util.chownbyname(log_file, u, g)
  File "/usr/lib/python2.7/site-packages/cloudinit/util.py", line 1134, in chownbyname
    raise OSError("Unknown user or group: %s" % (e))
OSError: Unknown user or group: 'getpwnam(): name not found: syslog'
2016-04-20 04:57:59,531 - util.py[DEBUG]: Running command ['ifconfig', '-a'] with allowed return codes [0] (shell=False, capture=True)
2016-04-20 04:57:59,542 - util.py[DEBUG]: Running command ['netstat', '-rn'] with allowed return codes [0] (shell=False, capture=True)
2016-04-20 04:57:59,559 - util.py[WARNING]: Route info failed: Unexpected error while running command.
Command: ['netstat', '-rn']
Exit code: -
Reason: [Errno 2] No such file or directory
Stdout: ''
Stderr: ''
2016-04-20 04:57:59,559 - util.py[DEBUG]: Route info failed: Unexpected error while running command.
Command: ['netstat', '-rn']
Exit code: -
Reason: [Errno 2] No such file or directory
Stdout: ''
Stderr: ''
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cloudinit/netinfo.py", line 173, in route_pformat
    routes = route_info()
  File "/usr/lib/python2.7/site-packages/cloudinit/netinfo.py", line 98, in route_info
    (route_out, _err) = util.subp(["netstat", "-rn"])
  File "/usr/lib/python2.7/site-packages/cloudinit/util.py", line 1565, in subp
    raise ProcessExecutionError(cmd=args, reason=e)
ProcessExecutionError: Unexpected error while running command.
Command: ['netstat', '-rn']
Exit code: -
Reason: [Errno 2] No such file or directory
Stdout: ''
Stderr: ''
```

**Comment by mwest44** [comment]
I'm not sure of the issue from the logs you've shown.  Are you able to ping the masters and zookeeper nodes or did you log in from the console?  make sure that your zookeeper static IPs are outside the DHCP scope used for the Master VMs.

**Comment by julykobe** [comment]
Yes, I'm able to ping the three masters and zookeeper. And zookeeper static IPs are inside the Master VMs DHCP scope, I'll try to put it outside, but could you please tell me why? Thanks!

**Comment by sufiand** [comment]
Hi @julykobe,
The failure you are running into suggests that during the rollout process, photon-controller failed to reach out to the Mesos Master service on the Master VM. Can you please provide the output of "docker ps" command on the Mesos Master VM? 

Just to provide some context, when photon-controller rollouts different VMs in the cluster, depeneding on the type of VM such as Mesos Master, photon controller starts a container that is running the Mesos Master Service. Once that happens, photon-controller waits till the service is reachable. If not, then rollout process eventually fails. 

So, the failure you are running into could be one of the following issues:
1- The container for Mesos Master is not running.
2- There is a networking problem as-in, the container started by for some reason the VM is not reachable from the management VM.

You can also use curl or a browser to check if the Mesos service is actually running or reachable by doing http://<mesos-master-ip>:5050 

If it was running, this would open up Mesos's homepage.

**Comment by mwest44** [comment]
The reason the static IPs need to be outside the DHCP scope is so the master VMs don't get one of the IPs that you have statically assigned in the cluster create call.

**Comment by julykobe** [comment]
Thanks @sufiand 
The output of "docker ps" command on the Mesos Master VM is:

root@master-9a525da9-c32a-4645-a3b4-5b757ab1f247 [ ~ ]# docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

Seems mesos-master container is not running. I'm curious why such errors occur in cloud-init.log on Mesos Master VM.


@mwest44 Got it, I have tried to use IP outside the DHCP scope for zookeeper  but got the same result.

**Comment by julykobe** [comment]
I have tried to setup a Swarm cluster(one slave) with the same env. I failed at first time and succeeded at second... amazing! The error is the same with Mesos cluster(failed at creating Swarm slave).

```
➜  Downloads ./photon cluster create -n Swarm2 -k Swarm --dns 10.110.160.1 --gateway 10.110.170.253 --netmask 255.255.255.0 --etcd1 10.110.170.52 -s 1
Using target 'http://10.110.170.48:9000'
etcd server 2 static IP address (leave blank for none):

Creating cluster: Swarm2 (SWARM)
  Slave count: 1

Are you sure [y/n]? y
Cluster created: ID = 0edf7a20-b15b-48a4-8594-eaf3afc57479
Note: the cluster has been created with minimal resources. You can use the cluster now.
A background task is running to gradually expand the cluster to its target capacity.
You can run 'cluster show 0edf7a20-b15b-48a4-8594-eaf3afc57479' to see the state of the cluster.
```


**But I can't access  http://[Swarm_Master_IP]/ui ....on Swarm Master VM, **

```
root@master-40427034-65eb-4ebd-96f7-95efbcd5ee86 [ / ]# docker ps
Get http:///var/run/docker.sock/v1.20/containers/json: dial unix /var/run/docker.sock: no such file or directory.
* Are you trying to connect to a TLS-enabled daemon without TLS?
* Is your docker daemon up and running?
```

**Comment by sufiand** [comment]
@julykobe - For failure in Mesos cluster provisioning, can you please copy the output of the log file /var/log/mesos-master.log.

From the output of the CLI, it seems that your swarm cluster deployment worked. The Note in the output can be ignored because your swarm cluster only had one slave which did get created. We will have this fixed in the CLI, to not print the message where the cluster only has one slave node. Swarm does not have a UI interface, however, you can call into swarm's info API at http://swarm-master:8333/info.

**Comment by julykobe** [comment]
@sufiand Thanks! Seems https://github.com/vmware/photon-controller/wiki/deploy-swarm#validate-cluster-creation should be updated.

I'll deploy another Mesos cluster to provide you the log.

**Comment by julykobe** [comment]
```
root@master-f3cc6017-ac8f-4c09-9b03-dde2af417cd3 [ /var/log ]# cat mesos-master.log
Starting mesos master
root@master-f3cc6017-ac8f-4c09-9b03-dde2af417cd3 [ /var/log ]#
```

**Comment by julykobe** [comment]
I found another interesting thing, from https://github.com/vmware/photon-controller/wiki/deploy-mesos#note-on-sizing--space , the master VM will have 512MB of RAM but `photon vm show [vm_id]` I found the master VM use a flavor named cluster-master-vm and have 8GB memory.

My resource-tick has a 30GB memory limit and there are 4 vms in my cluster, 3 master vm with 8GB and 1 zookeeper vm with 4GB, I wonder whether it affect the deployment?

**Comment by mwest44** [comment]
This is actually a cut/paste error in the documentation.  In the Fusion/Workstation versions, I created custom flavors to make the mesos cluster very small.  Your default cluster will use the values from the default Cluster flavors.   Photon flavor list will show you those values.   Also, if the values are too large for your environment, you will see a Reserve Resource error when trying to create the VMs, rather than some other error during cluster setup in those VMs.

**Comment by julykobe** [comment]
@mwest44 Got it. Thanks!

Just a feedback:
I have tried to use another env with two ESXi hosts and the deployment run smoothly. Still not sure whether the number of hosts affect the deployment.
