### ISSUE TITLE
Unable to adjust VM sizing or flavor

### ISSUE THREAD

**Issue by dustinmitton** [vmware/photon-controller#26]
Once a project VM has been created using an image/flavor, there isn't any way to adjust the VM's resource sizing (CPU/Memory/disk) without physically modifying the VM on the ESXi host itself. If this adjustment is made, the VM does not report to the Photon Controller of it's new sizing and adjust the usage within the Ticket/Project/Tenant definition.

The example I'll use is when deploying the Mesos cluster on Photon Controller using a custom cluster-tiny-vm flavor (1 CPU, 1 GB, 1 Disk). After stopping the Mesos-slave VM and editing the settings to increase the vCPU to 4 and the memory to 8 GB using the vSphere Client, I started the VM again and refreshed the Photon Controller UI page and noticed that the resource load (CPU/Memory) did not increase past the original total of 6 vCPU and 6 GB of ram (total of 3 x Mesos-master, 1 x zookeeper, 1 x marathon and 1 x Mesos-slave VMs).

Having a feature within the Photon CLI and/or Photon Controller UI to allow the dynamic application of a different Flavor, or manual override of CPU/Mem/Disk sizing on the VM would be extremely helpful with cluster resources growth. Once this adjustment is made, the appropriate changes to the usage stats on the Tenant/Project/Ticket would also be reflected appropriately against the maximum sizing.

If this feature was to be added, I think it would also be important that when you run "photon vm show <id>" that the CPU and Memory sizing was displayed alongside the already available details of the disk/image/flavor of the VM.

Please note that I think this is an incredible product, and look forward to the continued improvements! Great Job so far!

**Comment by kmjung** [comment]
Hi Dustin,

Thanks for the feature suggestion! I’ve created a work item in the icebox of our Pivotal Tracker: https://www.pivotaltracker.com/story/show/118596357

To set expectations, we’ll have to incorporate this idea into our regular planning process; the feature is unlikely to be included in our upcoming 0.9 release.

Thanks
Ken
