### ISSUE TITLE
vagrant-guests-photon-0.0.1.gem download fails, looks like site is down?

### ISSUE THREAD

**Issue by lamw** [vmware/photon-controller#3]
```console
└─[127] <git:(master 8876ada) > ./update_dependencies.sh
Installing Photon plugin for Vagrant.
--2015-11-20 19:59:32--  http://10.146.64.234:8081/artifactory/vagrant-plugins/vagrant-guests-photon-0.0.1.gem
Connecting to 10.146.64.234:8081... failed: Operation timed out.
Retrying.
```

**Comment by schadr** [comment]
that seems to be a vmware internal address, it works only inf you are on the vmware network. let me submit a fix to point to a public address.

**Comment by schadr** [comment]
The publicly available location for the gem file is here

**Comment by bsiravara** [comment]
fixed. This is currently checked into the develop branch. We'll promote to Master shortly https://github.com/vmware/photon-controller/commit/e5071076c8325e1d0a44f234d3e7d096b99d4499
