### ISSUE TITLE
cannot add additional hosts

### ISSUE THREAD

**Issue by evinhernandez** [vmware/photon-controller#30]
I cannot seem to add additional hosts it fails as soon as i skip the meta data 
getting errors like the below 
C:\Users\evinh\Desktop\photon>photon host create --username root --password ph0ton --tag CLOUD --address 10.1.0.2
Host Metadata ({'key':'value'}. required by host of 'MGMT' tag):
Deployment ID:
Using target 'http://10.1.0.50:28080'
2016/05/17 15:36:41 Error: photon: { HTTP status: '404', code: 'NotFound', message: '', data: 'map[]' }

how can i create new cloud and management host

**Comment by evinhernandez** [comment]
com.vmware.photon.controller.api.common.filters.LoggingFilter: Response: /deployments//hosts [404] in

errors im seeing in the deployer log.

**Comment by schadr** [comment]
you need to provide the ID of your deployment when the cli prompts you, right after it asks you for the host meta data.

you can get the deployment Id by running ``photon deployment list``

**Comment by evinhernandez** [comment]
I have tried providing my id it fails with the same error.  unless im providing it wrong does it need to be in quotes or in brackets ?

**Comment by schadr** [comment]
did you try it with the -d flag for the deployment id 

```
photon host create --username root --password ph0ton --tag CLOUD --address 10.1.0.2 -d my-deployment-uuid
```

**Comment by schadr** [comment]
Let me look through the code and make sure that there is no regression.  What version of the cli are you using?

**Comment by schadr** [comment]
yes the is a bug, I'm working on a fix right now.

**Comment by schadr** [comment]
in the short term you can use non-interactive mode to add a host

```
photon -n host create --username root --password ph0ton --tag CLOUD --address 10.1.0.2 -d my-deployment-uuid
```
