### ISSUE TITLE
Photon Controller 0.9.0 - After successful deployment unable to make any update commands

### ISSUE THREAD

**Issue by karthick-selvaraj** [vmware/photon-controller#33]
Unable to execute any command which makes changes in the system. Example:

> photon -n tenant create Engineering 

command fails with below error:

Error: Photon: { HTTP Status:'403', code: 'SystemPaused', message: 'System is paused', data:'map[]' }

**Comment by kmjung** [comment]
Karthik, the system is in a paused state – please run a ‘system resume’ command to get things going.

**Comment by mwest44** [comment]
The actual command you need to run is
photon deployment resume

**Comment by pauldgifford** [comment]
update it is now 'photon deployment system_resume <id>'

**Comment by mwest44** [comment]
Sorry paul.  It really is 'photon deployment resume'
Please let me know if I have it wrong in any of the other docs I've sent out. I'll change it.

**Comment by pauldgifford** [comment]
<img width="710" alt="screenshot 2016-08-17 12 16 59" src="https://cloud.githubusercontent.com/assets/10437630/17747992/8d74aaba-6474-11e6-8b3c-891fe5e0369a.png">

**Comment by mwest44** [comment]
Is that the Windows CLI?   Maybe we haven't updated it.   Here is the latest linux version:
![2016-08-17_14-21-34](https://cloud.githubusercontent.com/assets/8647340/17748200/3a9359b0-6486-11e6-8d26-fe3cb6b92989.jpg)

**Comment by pauldgifford** [comment]
it sure is.  looks like we have a difference.
