### ISSUE TITLE
vib acceptance level issue.

### ISSUE THREAD

**Issue by simonzang** [vmware/photon-controller#37]
Confused. the software acceptance level of PP is community supported, but we had installed it on an ESXi host whose acceptance level is partner supported sucessfully. and when we try to use the 'esxcli software acceptance set' command to set the level to community support, we got below error message, 'Unable to set acceptance level of community due to installed VIBs VMware_bootbank_photon-controller-agentxxxxx having a lower acceptance level.' 

Three questions: 1, some customers don't allow community VIB to be installed, then how can they use PP? 2, why the acceptance level restruction is invalid in my case? 3, how to resolve this inconsistancy? have I must remove the VIB first?

**Comment by kmjung** [comment]
The Photon Controller VIB is currently community signed, and is installed using "esxcli software vib install --force". In the short term, you can use the same mechanism to install other VIBs.

In the near-term future, official Photon Controller releases will contain VIBs whose acceptance level is partner or higher.
