### ISSUE TITLE
Typo for Netmask environmental variable for Devbox

### ISSUE THREAD

**Issue by lamw** [vmware/photon-controller#4]
There's a typo in Devbox readme (https://github.com/vmware/photon-controller/tree/master/devbox-photon)

The following environmental variable
```
PUBLIC_NETWORK_MASK
```

should be

```
PUBLIC_NETWORK_NETMASK
```

**Comment by bsiravara** [comment]
Thanks @lamw , fixed https://github.com/vmware/photon-controller/commit/29ef5eeac08a849495673b923d4c3d907e9adda2
