### ISSUE TITLE
devbox vagrant up fails

### ISSUE THREAD

**Issue by uvgroovy** [vmware/photon-controller#40]
I'm trying to start the devbox, and i'm getting this error:

```
==> photon: + pip install -q -f file:///esxcloud/python/dist photon.controller.agent
==> photon:   Could not find any downloads that satisfy the requirement photon.controller.agent
==> photon: No distributions at all found for photon.controller.agent
==> photon: Storing complete log in /root/.pip/pip.log
```

Any idea why? I am trying to get my devbox working with and ESXi server so i can test some code that i changed, and i've been struggling for a few day
I've tried using the master branch but it seemed to depend on vmware urls that are not public (to access artifcatory). Then I switched to v0.9.1 and got this error.

Any help would be appreciated.

**Comment by uvgroovy** [comment]
Made some progress, after scraping everything and starting fresh, I am able to get the devbox running,
but when i try to deploy (with `photon system deploy`)
i get this error:

```
6648, imageDatastore:datastore1, useImageDatastoreForVms:true, authEnabled:false, loadBalancerEnabled:true), desired_state:PAUSED, tracing_info:TracingInfo(request_id:5a1e003c-c3b2-470c-a0c4-9ef92946964a))]. Error:
! java.lang.NullPointerException: null
! at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:210)
! at com.vmware.photon.controller.deployer.DeployerConfig.getImageFile(DeployerConfig.java:110)
! at com.vmware.photon.controller.deployer.DeployerConfig.getManagementImageFile(DeployerConfig.java:98)
! at com.vmware.photon.controller.deployer.service.client.DeploymentWorkFlowServiceClient.create(DeploymentWorkFlowServiceClient.java:90)
! at com.vmware.photon.controller.deployer.service.DeployerService.deploy(DeployerService.java:355)
! at com.vmware.photon.controller.deployer.gen.Deployer$Processor$deploy.getResult(Deployer.java:1513)
! at com.vmware.photon.controller.deployer.gen.Deployer$Processor$deploy.getResult(Deployer.java:1498)
! at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39)
! at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39)
! at org.apache.thrift.TMultiplexedProcessor.process(TMultiplexedProcessor.java:123)
! at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:286)
! at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
! at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
! at java.lang.Thread.run(Thread.java:745)
?5a1e003c-c3b2-470c-a0c4-9ef92946964a
```

I checked, and it seems to look for something in the management-vm folder, which is indeed empty... any idea what should go there?

**Comment by uvgroovy** [comment]
I tried using the "./prepare-devbox-deployment.sh" that seems create an image in that vm;
but it fails trying to download something from a non existent URL (vmware internal?):

https://ci.ec.eng.vmware.com/view/UI/job/ec-ui-mgmt-publish-docker-image-develop/lastSuccessfulBuild/artifact/ci/docker-image/esxcloud-management-ui.tar

**Comment by AlainRoy** [comment]
Hi Yuval,

The devbox has insufficient documentation, sorry. There is some tribal knowledge. I know that's not good, and I'm going to try to update the README in the devbox directory in the near future. 

Are you just trying to play with the devbox? Do development? 

Normally, I do the following to bring up a devbox:

1. Define a bunch of environment variables. These should be defined in README. We can double-check them if they don't work for you. 

2. Bring up the devbox with: `./gradlew :devbox:renew`

3.  
```
cd ruby/integration_tests
bundle exec rake cloudstore:seed; # Create deployment
bundle exec rake seed:host # Add host
```

The devbox is undergoing a bunch of development right now and over the next couple of weeks, so there may be some churn. But I think these steps will continue to work.

**Comment by uvgroovy** [comment]
I'm trying to add an ability to create disk from non empty existing image (like for a vm with a non empty data partition)
Eventually what i ended up doing is to copy the managment-ui container from another photon installation i had and using the prepare script it eneded up work.

trying to use "./gradlew :devbox:renew" from master branch also failed for me due to internal vmware urls.. i ended up using prepare-devbox-deployment.sh in git tag "v0.9.1", and modified it a bit to use managment-ui container I exported.
