### ISSUE TITLE
Updated Swarm, K8s and Mesos VMDK

### ISSUE THREAD

**Issue by gregorkistler** [vmware/photon-controller#47]
Hi,

are there any chances of getting updated VMDKs (especially in my case for Docker Swarm)? The one provided here https://s3.amazonaws.com/photon-platform/artifacts/cluster/photon-swarm-vm-disk1.vmdk is still based on TP2.

Thank you very much.

**Comment by mwest44** [comment]
We will definitely update the kubernetes image prior to our q4 release.  It will go to either 1.3 or 1.4 depending on the timing of 1.4 release.   You will see some additional capability as well

**Comment by embano1** [comment]
So what is the actual release process (schedule) for those VMDK files? Will there be an automatic CI/CD process to generate VMDKs whenever new Docker/ K8s/ Mesos (PROD) versions are released or is it a manually driven process for updating these images? 

Thank you.

**Comment by mwest44** [comment]
Going forward we will test the supported cluster images in our CI/CD pipeline.  So there will be supported images with each release.  I expect that it will be on the releases page with the other released bits, though we have not set that up yet.

**Comment by gregorkistler** [comment]
Will close this one here as we should already have newer releases meanwhile.
