### ISSUE TITLE
Dev Box broken

### ISSUE THREAD

**Issue by jeromeh66** [vmware/photon-controller#5]
When I tried to run "vagrant up", I got the following error:

==> photon: FAILURE: Build failed with an exception.
==> photon: 
==> photon: * What went wrong:
==> photon: Could not resolve all dependencies for configuration ':common-dcp:compile'.
==> photon: > Could not find com.vmware.dcp:dcp-common:0.2.0-20151114.004439-3.
==> photon:   Searched in the following locations:
==> photon:       file:/root/.m2/repository/com/vmware/dcp/dcp-common/0.2.0-SNAPSHOT/dcp-common-0.2.0-20151114.004439-3.pom
==> photon:       file:/root/.m2/repository/com/vmware/dcp/dcp-common/0.2.0-SNAPSHOT/dcp-common-0.2.0-20151114.004439-3.jar
==> photon:       https://repo1.maven.org/maven2/com/vmware/dcp/dcp-common/0.2.0-SNAPSHOT/dcp-common-0.2.0-20151114.004439-3.pom
==> photon:       https://repo1.maven.org/maven2/com/vmware/dcp/dcp-common/0.2.0-SNAPSHOT/dcp-common-0.2.0-20151114.004439-3.jar
==> photon:       http://oss.sonatype.org/content/repositories/snapshots/com/vmware/dcp/dcp-common/0.2.0-SNAPSHOT/dcp-common-0.2.0-20151114.004439-3.pom
==> photon:       http://oss.sonatype.org/content/repositories/snapshots/com/vmware/dcp/dcp-common/0.2.0-SNAPSHOT/dcp-common-0.2.0-20151114.004439-3.jar
==> photon:       http://dl.bintray.com/vmware/lightwave-maven/com/vmware/dcp/dcp-common/0.2.0-SNAPSHOT/dcp-common-0.2.0-20151114.004439-3.pom
==> photon:       http://dl.bintray.com/vmware/lightwave-maven/com/vmware/dcp/dcp-common/0.2.0-SNAPSHOT/dcp-common-0.2.0-20151114.004439-3.jar
==> photon:   Required by:
==> photon:       java:common-dcp:0.1.0-SNAPSHOT
==> photon: 
==> photon: * Try:
==> photon: Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
==> photon: BUILD FAILED

**Comment by kmjung** [comment]
The location of the Xenon jars is changing as the Xenon folks move from snapshots to proper releases. This should be fixed in the develop branch today.

**Comment by molteanu** [comment]
Fix for the build break was checked into the develop branch. https://github.com/vmware/photon-controller/commit/f4980bf57e7e72e75936fa5fa0a636fbfdf4eca1
