### ISSUE TITLE
Failed to deploy VM: postNFCData failed 

### ISSUE THREAD

**Issue by medvedzver** [vmware/photon-controller#58]
Hi!

I've installed latest ESXi to VMWare Fusion, successfully loaded a vmware ESXi UI.
I'm trying to deploy a Photon Controller as described 
https://vmware.github.io/photon-controller/assets/files/Photon_Controller_Getting_Started_Guide_20151116.pdf
I have 4 Core CPU and 8 gigs of RAM.
I've setted up static IP address to ESXi host. 
I have a default datastore with 36gigs.
I'm not sure how to check "It is not managed with vCenter" but I guess it's not.

I've downloaded latest pc-installer and I'm trying to create/register a vm. I've chosen "VM Network" as network and left everything else default. After I click finish host creation fails with the error
`Failed to deploy VM: postNFCData failed `

Then I see this host with status `Normal` in my list of hosts. I can power it on, and I see on a load screen that it tries to boot from the network. It fails with `Operation System not found` error. The boot order in BIOS has network boot in the last row, so I guess it didn't find anything else to boot from.

Can you please help me with this problem? Any advices where can I find more logs? Do I need to reserve one more static IP address somehow?

**Comment by AlainRoy** [comment]
When you say you got the latest installer, what do you mean, exactly? That getting started guide is for the version under development--it hasn't quite been released. 

When you say "I see this host with status Normal...", what do you mean by "host"? Do you mean "ESXi host", or do you mean "Photon Controller VM"? The term host is a bit over-used, sorry about that.

**Comment by medvedzver** [comment]
@AlainRoy Thanks for quick response!
I've downloaded ESXi iso from https://my.vmware.com/group/vmware/evalcenter?p=free-esxi6. Mounted it to Fusion and installed ESXi from this iso to Fusion VM.

The latest Photon Controller I took from https://github.com/vmware/photon-controller/releases, file named `installer-vm.ova`.

The host with status normal is the host in the ESXi UI. I think it's a PC installer VM, not the OC itself. When I click `Virtual Machines` at the Navigator at the left. Also, right now I can't connect to this host at all. I can't even started it. I get `The attempted operation cannot be performed in the current state (Powered Off).`

**Comment by mwest44** [comment]
I haven't tried the latest builds on Fusion, but there has been a bug in the Host Client that limited the size of the OVA that it can deploy.  Try to deploy the installer VM with ovftool.  Here is sample syntax for the ovftool deployment:

 
![image](https://cloud.githubusercontent.com/assets/8647340/20309284/62111182-ab15-11e6-8ccf-e83ba791c7fe.png)

**Comment by medvedzver** [comment]
@mwest44 Thanks! It deployed successfully. Maybe it's because of props. I didn't specified them in UI, because I didn't know that you have to specify them.
