### ISSUE TITLE
devbox-photon/install_photon_plugin.sh Error

### ISSUE THREAD

**Issue by jeromeh66** [vmware/photon-controller#6]
if [ -n DEVBOX_VAGRANT_PLUGIN_URL ] should be if [ -n "$DEVBOX_VAGRANT_PLUGIN_URL" ]; otherwise, download of vagrant-guests-photon-0.0.1.gem will fail.

**Comment by ashoksekar07** [comment]
Thanks for pointing this out @jeromeh66. This should be fixed in develop branch shortly.

**Comment by ashoksekar07** [comment]
Fix is checked into develop branch  https://github.com/vmware/photon-controller/commit/e296b48e1bd5bce6ebdde23612c79bafac5d3303
