### ISSUE TITLE
Failed to download photon client 1.1 for mac and linux from github with an error.

### ISSUE THREAD

**Issue by simonzang** [vmware/photon-controller#60]
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>releases/43398044/0986462a-ad6f-11e6-8f7d-9acbb7a07fc8.0-5de1cb7</Key><RequestId>825C8E2DBF7A05BA</RequestId><HostId>Eishhi7SBR28Lfc2uE5FZLuOpuiR4/EesuYRxN8+9r3YpsXjLG8wL27ymovkY0dnlODESdRgGz4=</HostId></Error>

**Comment by AlainRoy** [comment]
Sorry about that--we'll fix it asap.

cc: @schadr is this something you can do when you have a chance?

**Comment by schadr** [comment]
Re-uploaded the binaries, the download should work now.
