### ISSUE TITLE
Photon controller agent unable to start on the host

### ISSUE THREAD

**Issue by govint** [vmware/photon-controller#62]
Got the new installer VM (installer-vm-1.1.0-5de1cb7.ova ) and tried the installation. The deployment fails at the "prepare" phase. The logs on the host are printing this repeatedly, installer VM reports a timeout in its logs.

 ---
GITHASH:0
CHANGE:0
BRANCH:vsphere60p04
UID:204883950
VMTREE:
VMBLD:obj
BUILDTAG:developer
BUILDNUMBER:00000

 ---
 ls /usr/lib
cim                                            libcimcclient.so.0                             libsfcHttpAdapter.so.0                         libvmksignverify_32.so
hostprofiles                                   libcmpiCppImpl.so.0                            libsfcIndCIMXMLHandler.so.0                    libvmwauth.so
libarchive.so.2                                libcmpisfcc.so.1                               libsfcInternalProvider.so.0                    libwrapvmwauth.so
libboost_bzip2-gcc46-mt-d-1_55.so.1.55.0       libesxclic.so                                  libsfcInteropProvider.so.0                     libwsman.so.1
libboost_chrono-gcc46-mt-d-1_55.so.1.55.0      libhd.so.18                                    libsfcInteropServerProvider.so.0               libwsman_client.so.1
libboost_filesystem-gcc46-mt-d-1_55.so.1.55.0  libipmi.so                                     libsfcObjectImplSwapI32toP32.so.0              libwsman_clientpp.so.0
libboost_iostreams-gcc46-mt-d-1_55.so.1.55.0   libpyCmpiProvider.so                           libsfcProfileProvider.so.0                     libwsman_curl_client_transport.so.1
libboost_python-gcc46-mt-d-1_55.so.1.55.0      libsfcBasicPAMAuthentication.so.0              libsfcQualifierProvider.so.0                   libwsman_server.so.1
libboost_regex-gcc46-mt-d-1_55.so.1.55.0       libsfcBrokerCore.so.0                          libsfcUtil.so.0                                locale
libboost_system-gcc46-mt-d-1_55.so.1.55.0      libsfcCertificateAuthentication.so.0           libslp.so.1                                    openwsman
libboost_zlib-gcc46-mt-d-1_55.so.1.55.0        libsfcCimXmlCodec.so.0                         libsqlite3.so                                  pycim
libcimRPmodule.so                              libsfcClassProviderGz.so.0                     libsqlite3.so.0                                vmware
libcimcClientSfcbLocal.so.0                    libsfcElementCapabilitiesProvider.so.0         libsqlite3.so.0.8.6                            xorg
libcimcClientXML.so                            libsfcFileRepository.so.0                      libticket.so.0

 ---
/var/run/log/photon-controller-agent.log

WARNING  [2016-11-21 13:33:18,267] [1000021532:1000021531:Thread-1] [agent.py:start_wrapper:217] __main__: Traceback (most recent call last):
WARNING  [2016-11-21 13:33:18,267] [1000021532:1000021531:Thread-1] [agent.py:start_wrapper:217] __main__:   File "/var/lib/jenkins/workspace/esxcloud-python/python/create_vib.TNsva/vib/payloads/agent/opt/vmware/photon/controller/2.7/site-packages/agent/agent.py", line 210, in start_wrapper
WARNING  [2016-11-21 13:33:18,268] [1000021532:1000021531:Thread-1] [agent.py:start_wrapper:217] __main__:   File "/var/lib/jenkins/workspace/esxcloud-python/python/create_vib.TNsva/vib/payloads/agent/opt/vmware/photon/controller/2.7/site-packages/agent/agent.py", line 74, in start
WARNING  [2016-11-21 13:33:18,268] [1000021532:1000021531:Thread-1] [agent.py:start_wrapper:217] __main__:   File "/var/lib/jenkins/workspace/esxcloud-python/python/create_vib.TNsva/vib/payloads/agent/opt/vmware/photon/controller/2.7/site-packages/common/plugin.py", line 117, in load_plugins
WARNING  [2016-11-21 13:33:18,268] [1000021532:1000021531:Thread-1] [agent.py:start_wrapper:217] __main__:   File "/var/lib/jenkins/workspace/esxcloud-python/python/create_vib.TNsva/vib/payloads/agent/opt/vmware/photon/controller/2.7/site-packages/host/plugin.py", line 32, in init
WARNING  [2016-11-21 13:33:18,268] [1000021532:1000021531:Thread-1] [agent.py:start_wrapper:217] __main__:   File "/var/lib/jenkins/workspace/esxcloud-python/python/create_vib.TNsva/vib/payloads/agent/opt/vmware/photon/controller/2.7/site-packages/host/hypervisor/hypervisor.py", line 37, in __init__
WARNING  [2016-11-21 13:33:18,269] [1000021532:1000021531:Thread-1] [agent.py:start_wrapper:217] __main__:   File "/var/lib/jenkins/workspace/esxcloud-python/python/create_vib.TNsva/vib/payloads/agent/opt/vmware/photon/controller/2.7/site-packages/host/hypervisor/hypervisor.py", line 66, in create_host_client
WARNING  [2016-11-21 13:33:18,269] [1000021532:1000021531:Thread-1] [agent.py:start_wrapper:217] __main__:   File "/var/lib/jenkins/workspace/esxcloud-python/python/create_vib.TNsva/vib/payloads/agent/opt/vmware/photon/controller/2.7/site-packages/host/hypervisor/esx/attache_client.py", line 47, in <module>
WARNING  [2016-11-21 13:33:18,269] [1000021532:1000021531:Thread-1] [agent.py:start_wrapper:217] __main__: ImportError: libboost_python-gcc46-mt-1_55.so.1.55.0: cannot open shared object file: No such file or directory
INFO     [2016-11-21 13:33:19,313] [1000021554:1000021552:Thread-1] [agent.py:start:68] __main__: Startup config: {'datastores': None, 'host_service_threads': 20, 'logging_file_backup_count': 10, 'stats_store_port': 0, 'bootstrap_poll_frequency': 5, 'port': 8835, 'log_level': u'debug', 'config_path': '/etc/opt/vmware/photon/controller', 'workers': 32, 'hostname': None, 'utilization_transfer_ratio': 9, 'no_syslog': False, 'thrift_timeout_sec': 3, 'memory_overcommit': 1.0, 'logging_file_size': 10485760, 'image_datastores': None, 'heartbeat_interval_sec': 10, 'auth_enabled': False, 'cpu_overcommit': 16.0, 'stats_store_endpoint': None, 'stats_enabled': False, 'control_service_threads': 1, 'heartbeat_timeout_factor': 6, 'wait_timeout': 10, 'host_id': None, 'logging_file': '/scratch/log/photon-controller-agent.log', 'console_log': False, 'deployment_id': None, 'management_only': False, 'stats_host_tags': None}
INFO     [2016-11-21 13:33:19,746] [1000021554:1000021552:Thread-1] [plugin.py:load_plugins:112] common.plugin: Plugins found: [<host.plugin.HostPlugin object at 0x380adc2c>, <agent.plugin.AgentControlPlugin object at 0x380cae2c>, <stats.plugin.StatsPlugin object at 0x380f2b6c>]

**Comment by mwest44** [comment]
The 1.1 release requires ESXi 6.0P4 and does not yet support 6.5.  We will be adding 6.5 in a patch release.  I was able to successfully deploy this build onto my ESXi hosts running 6.0P4.

**Comment by govint** [comment]
Yes I'm running on ESX 6.0p4

**Comment by mwest44** [comment]
then you should verify that you have ssh enabled on all of your hosts

**Comment by longzhou** [comment]
>>> [agent.py:start_wrapper:217] main: ImportError: libboost_python-gcc46-mt-1_55.so.1.55.0: cannot open shared object file: No such file or directory

It seems you have /usr/lib/libboost_python-gcc46-mt-d-1_55.so.1.55.0, and the file name has extra '-d-' compared to the expected file. Are you using an official release of ESXi?

You can probably try to create a symlink to see if that solves the problem.

**Comment by govint** [comment]
I'm using a sandbox build of 6.0p04 debug build Is that the issue, I did
see the difference in lib names. I'll try a release build.

**Comment by govint** [comment]
Yes, ssh is enabled but let me try with a release build

**Comment by govint** [comment]
Rebuilt the ESX to use a release version and am able to install ok. Thanks.
