### ISSUE TITLE
Allow a client to provide custom meta-data to be stored for a persistent disk

### ISSUE THREAD

**Issue by govint** [vmware/photon-controller#64]
Clients creating persistent disks should be able to have the controller persist meta-data on behalf of the client. The meta-data is generated by the client and understood only by the client. To keep it simple, the data could be fixed size (say max 4k). The create disk API should allow the user to provide a map thats persisted for the disk and returned to the client when disk is fetched via its ID.

Use case would be to describe the disk  contents - block size, format, key-value pairs (owner, etc.) used by the client.

**Comment by giskender** [comment]
Thanks for your feedback. We will work on custom properties with key-value in the next release.
