### ISSUE TITLE
Support creating a clone of an existing persistent disk

### ISSUE THREAD

**Issue by govint** [vmware/photon-controller#65]
Users should be able to create data backups for container data (on persistent disks) and one way to do that would be to be able to make a snap/clone of an existing volume to create a new disk. The user cqan create a backup and then delete the cloned disk.

The disk create API (/project/<id>/disks) could allow specifying the ID of an existing disk to clone from.

**Comment by giskender** [comment]
Thanks for this feature request. We created a bug for this and will work on it.
