### ISSUE TITLE
503 Service Unavailable

### ISSUE THREAD

**Issue by medvedzver** [vmware/photon-controller#67]
Hi!

I have an ESXi host and Photon Controller on different VMs in a Fusion. 
Photon controller is a VM from PhotonControllerDevbox-11-12-15.ova, that I downloaded from somewhere.
I have a photon CLI on my local machine.

I issue the following command
`photon target set https://192.168.218.29:443 --nocertcheck`
`API target set to 'https://192.168.218.29:443'`

`photon host create --username root --password YourESXiVmPassword --tag CLOUD --address 192.168.209.31`
after entering Deployment ID and leaving host metadata empty I get
Using target 'https://192.168.218.29:443'
2016/11/22 08:24:49 Error: photon: HTTP 503: <html><body>\<h1>503 Service Unavailable\</h1>
No server is available to handle this request.
</body></html>

The same output I get when I do 
`photon deployment list`
Using target 'https://192.168.218.29:443'
2016/11/22 08:26:04 Error: photon: HTTP 503: <html><body>\<h1>503 Service Unavailable\</h1>
No server is available to handle this request.
</body></html>

If it's important - photon machine doesn't have an Internet access.
Can you please tell me what do I need to do to make it work? Where can I read the logs to fully understand the problem?

Thank you for you help!

**Comment by schadr** [comment]
Can you upload the logs in `/var/log/esxcloud` from all the vms and the installer-vm, thanks

**Comment by mwest44** [comment]
My suggestion is that you hold for a few weeks on this.   You are trying a version of PC that is more than a year old, and contained specific customizations to make it work in a very small nested Fusion environment.  Even if you get this to work, it doesn't represent the current product.  We will be delivering an easier way to deploy the current version thru Fusion in the coming weeks.

**Comment by medvedzver** [comment]
@schadr I don't have this file on my PC.  I have cloud-init.log. Do you need this one? 
Also I don't have a PC-installer machine running. I don't quite understand how to use installer and why I can't just use PC image I downloaded from 
https://s3.amazonaws.com/photon-platform/artifacts/user-workflow/PhotonControllerDevbox-11-12-15.ova

@mwest44 I'm trying to run it in Fusion. Do you mean PS is not meant to be running on Fusion now?

**Comment by mwest44** [comment]
Its kind of a long explanation.  The shortened version is that there is not enough resource on a single laptop to deploy the PC-installer VM and some configuration of nested ESXi host(s)/PC-mgmt VMs, then run the standard PC deployment process.  So, with the help of our engineers, I created an ova that is a PC mgmt VM and is pre-seeded with a deploymentID and an expectation of an ESXi host with a specific IP address.  All of this is based on code that was barely in Beta form a year ago.   

There is no reason that the current code available on github can't run in a Fusion VM other than the same issue with resources available on the laptop.  We are working on a new installer which will allow a single OVA/RPM deploy that will be much smaller and could run on your laptop.

**Comment by medvedzver** [comment]
@schadr Sorry for the delay, but I'm still having this issue. 
I've attached /var/log/cloud-init.log and /var/log/vboxadd-install.log 
[https://drive.google.com/file/d/0Bw9LNZMUPkxISDFMbVlYakllcWM/view](url)
[https://drive.google.com/file/d/0Bw9LNZMUPkxIRVM4b2Rael9TNzg/view](url)

Can you please tell me :
How do I restart photon controller? 
Where are the logs of photon controller? 

Also, I can't understand what is the difference between PC installed on this DevBox and the one that is installer-vm [(https://github.com/vmware/photon-controller/releases)](url)

Thanks for your help!

**Comment by medvedzver** [comment]
I think the problem was  with using VirtualBox. Fusion works fine.
