### ISSUE TITLE
Login problem, ssh into install-vm.ova ?

### ISSUE THREAD

**Issue by RedDevil69** [vmware/photon-controller#69]
Deployed install-vm with pre-defined password for admin and PCUser.
Unfortunately can't ssh.
Access denied.
Tried vSphere Console: root/vmware - not working
Ssh esxcloud / vmware as the user name / password -> not working

Installer version 1.1.0

**Comment by mwest44** [comment]
without seeing the ovftool command you used, its hard to say.  One thought I had is If you used a password with a character that gets interpreted by bash, you need to escape it in the ovftool command using \ in front of it.

**Comment by RedDevil69** [comment]
Used @

**Comment by mwest44** [comment]
Are you using the new Host Client or do you have vCenter installed and using the Web client?   I'm not sure you can set the attributes correctly using the Web Client.  You should also try a password without special chars and see if that works.

**Comment by RedDevil69** [comment]
Host Client, new and updated. Changed the pass without special chars.
Now it works directly from vSphere Console.
Thx for hint, good to add that information to the doc.
