### ISSUE TITLE
Unable to deploy stack in HA with Lightwave

### ISSUE THREAD

**Issue by RedDevil69** [vmware/photon-controller#75]
Deployment ends with error:
2017/01/04 11:52:48 Error: photon: Task 'dd6c5dd754542776d05e9' is in error state: {@step=={"sequence"=>"2","state"=>"ERROR","errors"=>[photon: { HTTP status: '0', code: 'DeploymentFailed', message: 'Deployment #dd6c5dd754542756c5fa0 failed: Container null of type Lightwave on VM 100.64.144.34 failed to become ready after 300 iterations', data: 'map[id:dd6c5dd754542756c5fa0 error:Container null of type Lightwave on VM 100.64.144.34 failed to become ready after 300 iterations]' }],"warnings"=>[],"operation"=>"PROVISION_CONTROL_PLANE_VMS","startedTime"=>"1483526767487","queuedTime"=>"1483526657350","endTime"=>"1483527167502","options"=>map[dd6c5dd754542756c5fa0:deployment]}}
API Errors: [photon: { HTTP status: '0', code: 'DeploymentFailed', message: 'Deployment #dd6c5dd754542756c5fa0 failed: Container null of type Lightwave on VM 100.64.144.34 failed to become ready after 300 iterations', data: 'map[id:dd6c5dd754542756c5fa0 error:Container null of type Lightwave on VM 100.64.144.34 failed to become ready after 300 iterations]' }]

Checked some threads.
ESXi version 6.0 P04 (ESXi600-201611001) - [https://github.com/vmware/photon-controller/issues/66](url)
Only 1 DNS server in config 

Lightwave is deployed on host and responding.
Reachable from pc-installer
Docker inside is active and responding.

Deployment yaml:
hosts:
  - address_ranges: 100.64.144.21
    username: root
    password: ***
    usage_tags:
      - MGMT
      - CLOUD
    metadata:
      MANAGEMENT_DATASTORE: datastore1
      MANAGEMENT_PORTGROUP: VM Network
      MANAGEMENT_NETWORK_NETMASK: 255.255.240.0
      MANAGEMENT_NETWORK_DNS_SERVER: 8.8.8.8
      MANAGEMENT_NETWORK_GATEWAY: 100.64.144.1
      MANAGEMENT_VM_IPS: 100.64.144.32
  - address_ranges: 100.64.144.22
    username: root
    password: ***
    usage_tags:
      - MGMT
      - CLOUD
    metadata:
      MANAGEMENT_DATASTORE: datastore2
      MANAGEMENT_PORTGROUP: VM Network
      MANAGEMENT_NETWORK_NETMASK: 255.255.240.0
      MANAGEMENT_NETWORK_DNS_SERVER: 8.8.8.8
      MANAGEMENT_NETWORK_GATEWAY: 100.64.144.1
      MANAGEMENT_VM_IPS: 100.64.144.33
  - address_ranges: 100.64.144.23
    username: root
    password: ***
    usage_tags:
      - MGMT
      - CLOUD
    metadata:
      MANAGEMENT_DATASTORE: datastore3
      MANAGEMENT_PORTGROUP: VM Network
      MANAGEMENT_NETWORK_NETMASK: 255.255.240.0
      MANAGEMENT_NETWORK_DNS_SERVER: 8.8.8.8
      MANAGEMENT_NETWORK_GATEWAY: 100.64.144.1
      ALLOWED_SERVICES: Lightwave
      MANAGEMENT_VM_IPS: 100.64.144.34
deployment:
  resume_system: true
  image_datastores:
    - datastore1
    - datastore2
    - datastore3
  auth_enabled: true
  sdn_enabled: false
  stats_enabled: false
  ntp_endpoint: a.b.c.d
  use_image_datastore_for_vms: true
  loadbalancer_enabled: true
  oauth_username: 'Administrator'
  oauth_tenant: 'esxcloud'
  oauth_password: 'Password'
  oauth_security_groups:
    - "esxcloud\\Administrators"
    - "esxcloud\\photonControllerAdmins"

**Comment by mwest44** [comment]
I don't know if this is the issue, but have you tried a stronger oauth_password?  I've always used something with at least one special char.  If that is the issue, we definitely need a better error message.

**Comment by RedDevil69** [comment]
will try, if not I will dump log

**Comment by RedDevil69** [comment]
No way @mwest44, that was pass :)

**Comment by RedDevil69** [comment]
keep going testing other staffs

**Comment by RedDevil69** [comment]
Destroyed env and tried once again to be sure that everything is fine, unfortunately error during deployment. Now with certificate.
2017/01/04 14:40:48 Error: photon: Task 'dd6c5dd754544dd596bd9' is in error state: {@step=={"sequence"=>"2","state"=>"ERROR","errors"=>[photon: { HTTP status: '0', code: 'DeploymentFailed', message: 'Deployment #dd6c5dd754544db52d608 failed: Generating certificate failed with exit code 1', data: 'map[id:dd6c5dd754544db52d608 error:Generating certificate failed with exit code 1]' }],"warnings"=>[],"operation"=>"PROVISION_CONTROL_PLANE_VMS","startedTime"=>"1483537067463","queuedTime"=>"1483536957277","endTime"=>"1483537247474","options"=>map[dd6c5dd754544db52d608:deployment]}}
API Errors: [photon: { HTTP status: '0', code: 'DeploymentFailed', message: 'Deployment #dd6c5dd754544db52d608 failed: Generating certificate failed with exit code 1', data: 'map[id:dd6c5dd754544db52d608 error:Generating certificate failed with exit code 1]' }]


[photon-controller.txt](https://github.com/vmware/photon-controller/files/684756/photon-controller.txt)

**Comment by alancivita** [comment]
Hello..  i think that the photon cli command doesn't cleanup properly the environment;

i suggest to manually remove the 3 agents vibs from the esxi (photon-controller-agent, envoy and lightwave) and then remove the *.0 and *.r0 certificates from /etc/vmware/ssl/ and  the afd.db from /etc/vmware/vmafd/db/ directory on your esxi hosts...only now try to redeploy everything
Alan

**Comment by alancivita** [comment]
did you also redeployed the photon Deployer vm?

**Comment by RedDevil69** [comment]
no

**Comment by alancivita** [comment]
usually i delete it when starting over..can you try it please?

**Comment by RedDevil69** [comment]
Total manual celan-up worked,
Is this only accurate method to complete redeploy the stack @mwest44 ?? hmm

**Comment by alancivita** [comment]
generally it should be enough delete the 
/etc/esxcloud/photon-controller-core/cloud-store/sandbox_19000 directory on the photon deployer instance .. you can reach it via ssh with username esxcloud, and the restart the deployer instance.
Be aware that after the restart the container esxcloud/installer_ui (docker ps -a will show you the containers) won't be running, you have to restart it manually:

so
docker ps  -a
CONTAINER ID        IMAGE                             COMMAND                  CREATED             STATUS              PORTS               NAMES
5ec63a931b30        esxcloud/installer_ui             "/bin/sh -c '/bin/bas"   3 weeks ago         Up 3 weeks                              ui_installer
7caa90e1e9de        esxcloud/photon-controller-core   "bash /etc/esxcloud/r"   3 weeks ago         Up 3 weeks                              photon-controller-core_installer

your 5ec63a931b30        esxcloud/installer_ui won't be running, you have to restart it with
docker restart 5ec63a931b30

hope this helps

Alan

**Comment by mwest44** [comment]
I have found that redeploying the installer after a failed attempt is the best method.  As far as the cert error, we had identified this as an issue we need to fix.

**Comment by RedDevil69** [comment]
@alancivita 
I used the steps before
@mwest44 
Redeploying works fine after fail, unfortunately do not work when deployed stack was destroyed and you destroyed env to do this once again.
Closing issue.
Thx.
