### ISSUE TITLE
No ./photon resource-ticket delete

### ISSUE THREAD

**Issue by RedDevil69** [vmware/photon-controller#81]
I discovered that after creation of the ticket in tenant you can't delete it or change.

There is no ./photon resource-ticket delete option.

Am I right ??

**Comment by mwest44** [comment]
That is true today.  We are revamping how we handle quota allocation in upcoming releases.  They will be mutable.

**Comment by fawadkhaliq** [comment]
@RedDevil69 in the latest release of Photon Controller [1], the support for resource-tickets delete/update ops does not exist. So this is expected. You should be able to check the list of available operations for API resources using the CLI or Swagger UI. As an example, here's the CLI output for resource-ticket from the 1.1.0 release.

```
~/ photon resource-ticket -h

NAME:
   photon resource-ticket - options for resource-ticket

USAGE:
   photon resource-ticket command [command options] [arguments...]

COMMANDS:
   create	Create a new resource-ticket
   show		Show resource-ticket info with specified name
   list		List all resource tickets
   tasks	List all tasks related to the resource ticket
   help, h	Shows a list of commands or help for one command
```

[1] https://github.com/vmware/photon-controller/releases/tag/v1.1.0

**Comment by RedDevil69** [comment]
@mwest44 thx waiting to implement that
@fawadkhaliq yep I seen that, thought that maybe there is some magic :)

**Comment by AlainRoy** [comment]
No magic, but we are working on it for the next release.
