### ISSUE TITLE
Photon controller 1.1 deployment failed on prepare deployment

### ISSUE THREAD

**Issue by misko566** [vmware/photon-controller#86]
Hi,

I'm trying to deploy photon controller 1.1  on ESXi 6.0 build 3620759.

There was missing last customisation page on ova deployment for standard vsphere client.

So I install vCenter 6.0 appliance on another host and I did ova deployment.

Then I run deployment wizard for another ESXi host without vCenter.

I have unknown error on prepare deployment.

I have local disks with different names on each ESXi.

Please can you tell me what else informations you need and where I can find logs? 

I have tried it many times and on different installations and still same result.

After failed deployment there is new photon virtual machine created on ESXi host but it has no ip address.

<img width="1134" alt="screen shot 2017-01-25 at 19 28 05" src="https://cloud.githubusercontent.com/assets/25368647/22347744/5d979e00-e409-11e6-9404-ce8108eeab2c.png">

**Comment by mwest44** [comment]
Photon controller requires 6.0U2 P4 version of ESXi

**Comment by AlainRoy** [comment]
Michael is correct--you need a newer version of ESXi. A bit more detail:

https://github.com/vmware/photon-controller/wiki/Tips,-Tricks,-and-Gotchas

**Comment by misko566** [comment]
Wow that was really fast response :).

I will try it today but here is 21:13 so I don't now if will be ready still today.

I need to deploy  Photon controller and Kubernetes and vitess so maybe I will ask more questions in the future :)

Thanks

**Comment by misko566** [comment]
Hi, now I have 4600944 build on stand alone ESXi host and same result.

It deploys virtual machine with generated name on correct  datastore "885845f4-bcde-489e-bd6b-1bfe4be89095"  and thats all. Still prepare deployemnt failed with inknown error.

I've tried system destroy  with cli and try deployment again but same result.

What can be wrong?

Thanks

**Comment by mwest44** [comment]
Its difficult to tell without a log or an error message.   system destroy doesn't always completely clean up the installer VM metadata after a deployment error (installer will change in the next release).  You might try deleting the installer VM, redeploy it and then run the system deploy.   If you still get an error, log in to the installer VM  (esxcloud/vmware) and post the logs from /var/log/esxcloud directory

**Comment by misko566** [comment]
Now it's working. After redeploying  ova and creating new yaml is photon finaly deployed.

So for others if you fail at deploying double check ESXi configuration and redeploy ova.
