### ISSUE TITLE
Photon persistent volume for Kubernetes

### ISSUE THREAD

**Issue by misko566** [vmware/photon-controller#87]
Hi,

How can I create persistent volume for kubernetes ova deployment 1.4.3 ?

It is possible to upgrade kubernetes to new version 1.5.2? How?

https://kubernetes.io/docs/user-guide/persistent-volumes/

Thanks

**Comment by mwest44** [comment]
You cannot do either one in this release.  We are working on both of those things for an upcoming release.

**Comment by misko566** [comment]
When will be release date of new release? 
Thanks

**Comment by mwest44** [comment]
we have not announced it yet.  I expect the first half of this year, however we have not exited the engineering stage where we have committed to specific functionality so I can confirm that we are planning to do it, but cannot commit to the timeframe.  How is that for political speak.

**Comment by misko566** [comment]
Thanks for response.

I hope that it will be there :)

**Comment by misko566** [comment]
Hi

It is possible to run persistent volume for example from nfs server on kubernetes on photon?

or any of different ways?

I can mount nfs share on photon os
http://www.virtuallyghetto.com/2016/01/quick-tip-how-to-mount-cifs-nfs-volumes-on-photon-os.html


Or there is no way how to run persistent volume on kubernetes when is deployed on photon ?

list of supported persistent technologies from kuberenetes documentation:

GCEPersistentDisk
AWSElasticBlockStore
AzureFile
AzureDisk
FC (Fibre Channel)
Flocker
NFS
iSCSI
RBD (Ceph Block Device)
CephFS
Cinder (OpenStack block storage)
Glusterfs
VsphereVolume
Quobyte Volumes
HostPath (single node testing only – local storage is not supported in any way and WILL NOT WORK in a multi-node cluster)
VMware Photon

**Comment by mwest44** [comment]
There is nothing that we provide to support K8 persistent volumes at this point.   You would have to manually attach the nfs volume to the appropriate VMs and create the volume.  Its nothing that we have tested as this point.

**Comment by mwest44** [comment]
no problem.  If you need more direct help you can send me email and we can talk about what you are trying to do mwest@vmware.com
