### ISSUE TITLE
Could not find any downloads that satisfy the requirement photon.controller.agent

### ISSUE THREAD

**Issue by greencacti** [vmware/photon-controller#9]
When I try to start dev box with "vagrant up", it always report the following error:
==> photon: ++ hash -r
==> photon: + pip install -q -f file:///esxcloud/python/dist photon.controller.agent
==> photon:   Cannot fetch index base URL https://pypi.python.org/simple/
==> photon:   Could not find any downloads that satisfy the requirement photon.controller.agent
==> photon: No distributions at all found for photon.controller.agent
==> photon: Storing complete log in /root/.pip/pip.log

**Comment by anfernee** [comment]
Hey @greencacti ,

It basically means the installer failed to fetch dependency packages from pypi. Can you double check the Internet connectivity, or if you are behind any kind of corporate firewall? 

Thanks,
Anfernee

**Comment by kmjung** [comment]
This was root caused as a network connectivity issue.
